version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_REPLICA_IP=127.0.0.1
      - REDIS_REPLICA_PORT=7000
      - REDIS_PASSWORD=password
    networks:
      - app-tier
    ports:
      - '7000:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_REPLICA_IP=127.0.0.1
      - REDIS_REPLICA_PORT=7001
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD= password
      - REDIS_PASSWORD= password
    ports:
      - '7001:6379'
    depends_on:
      - redis
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD= password
      - REDIS_MASTER_HOST=127.0.0.1
      - REDIS_MASTER_PORT_NUMBER=7000
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      - app-tier